<a href="https://colab.research.google.com/github/Himabindugssn/Python-Basics/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

##Array

In [0]:
arr_1=[1,2,3]
arr_1+=1

TypeError: ignored

In [0]:
arr_2=np.array([1,2,3])
arr_2+=1

In [0]:
arr_2

array([2, 3, 4])

In [0]:
arr_3=arr_2 +2
arr_3

array([4, 5, 6])

In [0]:
arr_2*arr_3

array([ 8, 15, 24])

In [0]:
arr_2+arr_1

array([3, 5, 7])

In [0]:
arr_3[1]

5

arrays behave like lists..

In [0]:
arr_2.shape   #rows,columns

(3,)

In [0]:
np.array([[1,2,3],["himu"]])

array([list([1, 2, 3]), list(['himu'])], dtype=object)

In [0]:
l=[1,2,9,2,7]
a=np.array(l)
a

array([1, 2, 9, 2, 7])

In [0]:
type(l)

list

In [0]:
type(a)

numpy.ndarray

In [0]:
a.dtype

dtype('int64')

In [0]:
b=np.array([1,2,"a",5])
b.dtype

dtype('<U21')

In [0]:
b.size

4

In [0]:
b.shape

(4,)

In [0]:
b.ndim  #dimension of array

1

In [0]:
b.fill(2)  #fills the array i.e. replaces all the elements of the array with the given argument
b

array(['2', '2', '2', '2'], dtype='<U21')

##Indexing of matrices

In [0]:
m=np.array([[1,2,3],
            [4,5,6],
           ])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
m.shape

(2, 3)

In [0]:
m.size  #2*3

6

In [0]:
m.ndim #matrix is a 2D array

2

In [0]:
#for getting "3" in m matrix:
m[0][2]

3

In [0]:
m[0][2]=90
m

array([[ 1,  2, 90],
       [ 4,  5,  6]])

In [0]:
n=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
n[1]  #2nd row(0-1st row;1-2nd row)

array([4, 5, 6])

In [0]:
n[:,2] #3rd column([:,0]-1st column ); ':' colon - takes all the rows, 2 takes 3rd element of all rows

array([3, 6, 9])

In [0]:
#for printing first two elements of the 2nd row
n[1,0:2]

array([4, 5])

##Copy , Arange and Random

###COPY

In [0]:
p=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [0]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
p2=p
p2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#change the (1,2) element from 6 to 600
p2[1,2]=600
p2

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [0]:
p

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

This shows that a change in p2 also created change in p. This means that p hasn't been copied to p2 but both p &p2 have same ID value with different names.So to copy a matrix do the following:

In [0]:
pc=p.copy()
pc

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

In [0]:
pc[1,2]=90
pc

array([[ 1,  2,  3],
       [ 4,  5, 90],
       [ 7,  8,  9]])

In [0]:
p

array([[  1,   2,   3],
       [  4,   5, 600],
       [  7,   8,   9]])

Hence p has been successfully copied to pc

###Arange

In [0]:
ar=np.arange(0,100,20)  #This is read as from 0 to 100 every 20th number.
ar                      #arange is read as 'a' 'range'

array([ 0, 20, 40, 60, 80])

###Random

In [0]:
mn=np.random.rand(10)  #random.rand(20) - means generates 20 numbers in b|w 0 and 1
mn

array([0.23771212, 0.20106805, 0.61506417, 0.59696264, 0.81172652,
       0.13811438, 0.7946882 , 0.47270776, 0.32381735, 0.77784817])

##Data type and Conversion

In [0]:
t=np.array([1,2,3],dtype=np.float64)
t

array([1., 2., 3.])

In [0]:
t.nbytes

24

24/3= 8. Each number took 8 bytes

In [0]:
t1=np.array([1,2,3],dtype=np.float32)
t1

array([1., 2., 3.], dtype=float32)

In [0]:
t1.nbytes

12

12/3= 4 bytes per number. 32 bit consumes less memory than 64 bits

In [0]:
h=np.array([1,"2",9.0,"himu"])
h

array(['1', '2', '9.0', 'himu'], dtype='<U21')

In [0]:
hnew=np.array([1,"2",9.0,"himu"],dtype=np.object)
hnew

array([1, '2', 9.0, 'himu'], dtype=object)

In [0]:
h*3

TypeError: ignored

In [0]:
hnew*3


array([3, '222', 27.0, 'himuhimuhimu'], dtype=object)

dtype = object keeps the element as it is without forcibly changing the datatype. Hence * 3 is operated on every element of hnew but not h.


np.float32/64 for integers; np.object for array with elements of (various) types of data.

##Mathematical Functions

###np.sum()

In [0]:
aa=np.array([[1,2,3],[4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
np.sum(aa)

21.0

np.sum(array) prints the sum of all elements: 1+2+3+4+5+6=21 in the above eg.

In [0]:
ap=np.array([[1,2,"a"],["2",8,9.0]])
ap


array([['1', '2', 'a'],
       ['2', '8', '9.0']], dtype='<U21')

In [0]:
np.sum(ap)

TypeError: ignored

In [0]:
apn=np.array([[1,2,"a"],["2",8,9.0]],dtype=np.object)
apn

array([[1, 2, 'a'],
       ['2', 8, 9.0]], dtype=object)

In [0]:
np.sum(apn)

TypeError: ignored

In [0]:
ac=np.array([["a","b","c"],["d","e","f"]],dtype=np.object)
ac

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype=object)

In [0]:
np.sum(ac)

'abcdef'

This shows that np.sum can give sum of integers, strings(if dtype=np.object)

axis=0 : vertical; axis=1 : horizontal

In [0]:
aa=np.array([[1,2,3],[4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
np.sum(aa,axis=1)

array([ 6, 15])

([1+2+3],[4+5+6])

###prod()

In [0]:
aa=np.array([[1,2,3],[4,5,6]])
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
aa.prod()

720

aa.prod() gives 1*2*3*4*5*6

In [0]:
aa.prod(axis=1)

array([  6, 120])

[(1*2*3),(4*5*6)]

###min()

In [0]:
aa.min()

1

In [0]:
aa.min(axis=0)

array([1, 2, 3])

[min value in 1st column(1<4), 2nd column(2<5),3rd column(3<6)]

In [0]:
aa.min(axis=1)

array([1, 4])

###max()

In [0]:
aa.max()

6

In [0]:
aa.max(axis=1)

array([3, 6])

In [0]:
aa.max(axis=0)

array([4, 5, 6])

###argmin()

In [0]:
aa.argmin()  #min() gives minimum element value and argmin gives minimum 'index' 

0

In [0]:
aa.argmin(axis=0)

array([0, 0, 0])

In [0]:
aa.argmin(axis=1)

array([0, 0])

In [0]:
aa.argmax()

5

In [0]:
aa.argmax(axis=0)

array([1, 1, 1])

In [0]:
aa.argmax(axis=1)

array([2, 2])

###avg()

In [0]:
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
aa.mean()

3.5

In [0]:
aa.mean(axis=1)

array([2., 5.])

[(1+2+3)/3=2., (4+5+6)/3=5.]

###std() {standard deviation}

In [0]:
aa.std()

1.707825127659933

In [0]:
aa.std(axis=1)

array([0.81649658, 0.81649658])

In [0]:
aa.std(axis=0)

array([1.5, 1.5, 1.5])

std=    {[summation (x-mean)]/[n]} ^ 0.5

###var()   {statistical variability}

In [0]:
aa.var()

2.9166666666666665

###clip()

In [0]:
aa

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
aa.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

clip(a,b)  this means that all the numbers less than a should be a and greater than b should be b.

###round()

In [0]:
pp=np.array([1.22,3.4458,9.2])
pp

array([1.22  , 3.4458, 9.2   ])

In [0]:
pp.round()

array([1., 3., 9.])

In [0]:
pp.round(decimals=3)

array([1.22 , 3.446, 9.2  ])

##Order Functions

In [0]:
tt=np.array([[10.199,10.19,5.2],[3.3,81.68,9.7]])
tt

array([[10.199, 10.19 ,  5.2  ],
       [ 3.3  , 81.68 ,  9.7  ]])

###sort()

In [0]:
np.sort(tt)

array([[ 5.2  , 10.19 , 10.199],
       [ 3.3  ,  9.7  , 81.68 ]])

###argsort()

In [0]:
np.argsort(tt)   #instead of elements , their index will be printed

array([[2, 1, 0],
       [0, 2, 1]])

###searchsorted()

In [0]:
pp=np.arange(1,10,1)
pp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
k=np.array([1.2,8.9,5.3])
np.searchsorted(pp,k)

array([1, 8, 5])

This shows that (pp,k)=> elements of k can be placed after which no.s of pp

##Data Management Functions

In [0]:
y=np.arange(0,10,1)     #(0,10,1)==(10) i.e 0 -min no. and 1- step is basic set value
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
y.shape  #this shows a 1D array

(10,)

###reshaping

In [0]:
y.shape=5,2  #dividing the given list into 5 rows and 2 columns
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [0]:
y.reshape(5,2)  #the above way or this present cell's code are equivalent

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [0]:
w=np.arange(5)
w

array([0, 1, 2, 3, 4])

###newaxis: extra dimension

In [0]:
k=w[np.newaxis,:]
k

array([[0, 1, 2, 3, 4]])

In [0]:
k.shape

(1, 5)

In [0]:
k=w[:,np.newaxis]
k

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
k.shape

(5, 1)

np.newaxis creates new dimension. '':'' takes all the elements into that particular column

In [0]:
k=w[:,np.newaxis,np.newaxis]
k

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]]])

In [0]:
k.shape

(5, 1, 1)

###squeeze

In [0]:
#to remove the empty dimensions, use squeeze
k=w.squeeze()
k.shape

(5,)

In [0]:
i=np.arange(10)
j=i.reshape(2,5)
j

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

###transpose

In [0]:
j=j.transpose()
j

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [0]:
#transpose() can be written as 'T' also:
j=j.T
j

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
j.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

###concatenate

In [0]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
c=np.array([[11,22,33],[44,55,66]])
c

array([[11, 22, 33],
       [44, 55, 66]])

In [0]:
d=np.concatenate((b,c))  #default- added as extra rows
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [0]:
#to add as extra columns:
e=np.concatenate((b,c),axis=1)
e

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

###vstack & hstack

In [0]:
g=np.vstack((b,c))
g#v-vertical stacking //r axis=0 concatenate

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [0]:
np.hstack((b,c))

array([[ 1,  2,  3, 11, 22, 33],
       [ 4,  5,  6, 44, 55, 66]])

###flatten, ravel

In [0]:
l=g.flatten()  

In [0]:
l.shape

(12,)

In [0]:
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 22, 33],
       [44, 55, 66]])

In [0]:
s=g.ravel()
s

array([ 1,  2,  3,  4,  5,  6, 11, 22, 33, 44, 55, 66])

In [0]:
s.shape

(12,)

##Functions to create arrays

In [0]:
#To create 30 numbers between 0 & 30
np.linspace(0,10,30)   #all the points are equidistant ; this can't be done using arange

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

###To create a grid:

In [0]:
a=np.linspace(-10,10,5)
a


array([-10.,  -5.,   0.,   5.,  10.])

In [0]:
b=np.linspace(-5,5,5)
b

array([-5. , -2.5,  0. ,  2.5,  5. ])

In [0]:
a.shape

(5,)

In [0]:
b.shape

(5,)

In [0]:
x,y=np.meshgrid(a,b)


In [0]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [0]:
x.shape

(5, 5)

In [0]:
y

array([[-5. , -5. , -5. , -5. , -5. ],
       [-2.5, -2.5, -2.5, -2.5, -2.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 5. ,  5. ,  5. ,  5. ,  5. ]])

In [0]:
y.shape

(5, 5)

In [0]:
x,y=np.meshgrid(b,a)  #x(first variable) will have rows stacked one over other(vstack)
                      #y(second variable) will have columns stacked beside one another(hstock)

In [0]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

###more functions

In [0]:
y=np.r_[0:10:1]   #arguments //r to arange
#single row
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
y.shape

(10,)

In [0]:
z=np.c_[0:10:1]   

In [0]:
z.shape

(10, 1)

The terms seem confusing !!!.. It says c(column) but actually rows are being created..

In [0]:
z=np.c_[0:10:3]  #0 to 10 ; 3 steps increment
z

array([[0],
       [3],
       [6],
       [9]])

In [0]:
np.zeros(4)  #zeros not zero'e's !! Plz mind!!!

array([0., 0., 0., 0.])

In [0]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.ones((2,4))*100

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [0]:
np.zeros((2,5))+100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [0]:
np.ones((2,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [0]:
h=np.array([1,2,3,4])
h

array([1, 2, 3, 4])

In [0]:
np.zeros_like(h)  #converts already existing elements into zeros.//ry dowith ones

array([0, 0, 0, 0])

In [0]:
np.identity(3)  #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##Logical Operations

###abcd

In [0]:
a=np.array([1,1,2,1])  #array size should be same then only this would work..
b=np.array([1,1,1,0])


In [0]:
a==b

array([ True,  True, False, False])

In [0]:
a!=b

array([False, False,  True,  True])

In [0]:
a>=b

array([ True,  True,  True,  True])

In [0]:
a<=b

array([ True,  True, False, False])

##Random

In [3]:
z=np.random.rand(2,4)  #rand- no.s b|w 0 and 1 
z

array([[0.08791235, 0.55118788, 0.47973723, 0.36216099],
       [0.1355273 , 0.79690004, 0.1221452 , 0.26419735]])

In [0]:
#to remove decimals
np.set_printoptions(precision=3)


In [5]:
np.random.randint(30,size=(5,6))  #this is used (rand'int') for printing integers

array([[ 6,  2, 15, 16,  0,  8],
       [ 5, 21, 26, 28, 23,  4],
       [ 0, 18, 20,  3, 11, 24],
       [ 3, 25,  8,  6, 25,  6],
       [18, 13, 27, 27, 22,  0]])

In [6]:
np.random.randint(0,30,7)

array([ 5, 29, 11, 17, 15, 28,  2])

In [7]:
a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.random.shuffle(a)
a

array([16, 40, 62, 41, 99, 28, 90, 56, 86,  0, 64, 12, 26,  1, 47, 60, 88,
       11, 74,  8, 46, 31, 52, 75, 76, 44,  3, 53, 55, 22, 15, 39, 69, 72,
       54, 68, 96,  5, 10,  6, 20, 24, 48, 63, 78, 32, 23, 59, 77, 42, 70,
       49, 33, 83, 94, 58, 25, 80, 43, 79, 82, 61, 50, 71, 51, 95, 65, 91,
       84, 38, 17, 93, 37, 92, 85, 45, 98,  7, 73, 30, 29, 66, 87, 89, 13,
       27,  4, 21, 81, 36, 67,  2, 14, 97, 19, 34, 35,  9, 57, 18])

In [0]:
#seed controls random func.
np.random.seed(1)  #you can use any number instead of 1.; another set of random "fixed" values will be created

In [10]:
np.random.rand(3,3)   #no matter how many times you run this, the values won't change the particular "random" value set

array([[4.170e-01, 7.203e-01, 1.144e-04],
       [3.023e-01, 1.468e-01, 9.234e-02],
       [1.863e-01, 3.456e-01, 3.968e-01]])